version: '2'
services:
  rails: &app_base
    build:
      context: .
      dockerfile: "Dockerfile.development"
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    links:
      - db
      - redis
    environment:
      DATABASE_PASSWORD: "password123"
      DATABASE_USER: "root"
      DATABASE_HOST: "db"
  spring:
    <<: *app_base
    command: "bundle exec spring server"
    ports: []
  db:
    image: "mysql:5.6"
    environment:
      MYSQL_ROOT_PASSWORD: "password123"
    volumes_from:
      - data
  data:
    image: "busybox"
    volumes:
      - "/var/lib/mysql/data"
  redis:
    image: redis:2.8.19
    ports:
      - '8080:80'
    volumes_from:
      - data
